### ISSUE TITLE
Migration record Error

### ISSUE THREAD

**Issue by MarwaAbuEssa** [kfiroo/sendbird-nodejs#1]
hi,
i'm using sendbird-node for data migration from a firebase database . i'm using sb.migration.create to create channels and sb.channel.set_metadata to add meta data to them and it works great but when i'm trying to migrate messages to channels using  sb.migration.record , it respond with an error (Error. Messages[0] is invalid.) for some channels randomly !!!! .i tried it several time , each time i'm creating a test app at sendbird dashboard and run my endpoint , it gives this  (Error. Messages[0] is invalid.)  at the record step and not for a certain channel . it may once give error for one channel and once for multiplies channels !!!!!

please any help is appreciated 
Regards,
Marwa

**Comment by kfiroo** [comment]
Hey @MarwaAbuEssa I will try to look into your error as soon as I can.
Please note that this lib is only a Promise wrapper on top of `sendbird v2.0` api and should be used according to the `v2.0` docs, it might help.

**Comment by MarwaAbuEssa** [comment]
hi @kfiroo  , thanks a lot for your concern , i had just solved the problem by adding invite users step after creating channels and before recording messages to channels .

I don't know why that happened , although it works previously without the invite step !!! and it also works for some channels and not for others !!!.

I will post the issue for sendbird api support and see .
thanks again for your replay
regards ,

**Comment by kfiroo** [comment]
@MarwaAbuEssa Great :)
